using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem.Interactions;

public class UIManager : MonoBehaviour
{
    private static UIManager _instance;
    private Transform _uiRoot;
    private Dictionary<string, string> pathDict;
    private Dictionary<string, GameObject> prefabDict;
    public Dictionary<string, BasePanel> panelDict;

    // éœ€åœ¨åˆå§‹åŒ–å°±ç”Ÿæˆçš„UIç•Œé¢
    public ItemsInfo ItemsInfo;

    public static UIManager Instance
    {
        get
        {
            if(_instance == null)
            {
                _instance = new GameObject("UIManager").AddComponent<UIManager>();
            }
            return _instance;
        }
    }
    public Transform UIRoot
    {
        get
        {
            if(_uiRoot == null)
            {
                _uiRoot = GameObject.Find("Canvas").transform;
            }
            return _uiRoot;
        }
    }

    private void Awake()
    {
        print(this.name + " Awakeâ€”â€”------------");
        DontDestroyOnLoad(this);
        if (_instance != null && _instance != this)
        {
            Destroy(this.gameObject);
            return;
        }
        // å¦åˆ™ï¼Œè®¾ç½®è¿™ä¸ªå®ä¾‹ä¸ºå•ä¾‹
        _instance = this;


    }
    private void OnEnable()
    {
        print(this.name + " OnEnable------------");
        InitDicts();
        // InitMainUI();

    }
    private void OnDisable()
    {
        print(this.name + " OnDisable------------");
    }
    public void InitMainUI()
    {
        OpenPanel("ItemsInfo").GetComponent<ItemsInfo>();
    }
    public void RefreshManager()
    {
        EventSystem eventSystem = FindAnyObjectByType<EventSystem>();
        if (eventSystem == null)
        {
            GameObject eventSystemObject = new GameObject("EventSystem");
            eventSystemObject.AddComponent<EventSystem>();
            eventSystemObject.AddComponent<StandaloneInputModule>();
        }
        InitDicts();
        InitMainUI();
    }

    private void InitDicts()
    {

        prefabDict = new Dictionary<string, GameObject>();
        panelDict = new Dictionary<string, BasePanel>();
        // é…ç½®è·¯å¾„
        pathDict = new Dictionary<string, string>()
        {
            {UIConst.PackagePanel, "Package/PackagePanel"},

            {UIConst.Item, "MainUI/Item"},
            {UIConst.ItemsInfo, "MainUI/ItemsInfo"},
            {UIConst.GunInfo, "MainUI/GunInfo"},
            {UIConst.DialogBox, "MainUI/DialogBox"},
            {UIConst.ItemDetail, "MainUI/ItemDetail"},
            {UIConst.SelectBox, "MainUI/DialogSelectBox"},
            {UIConst.LoadingScene, "MainUI/LoadingScene"},
            
            {UIConst.HealthBarUI, "CharacterUI/Bar Holder"},
            {UIConst.PlayerMainUI, "CharacterUI/PlayerMainUI"},
            {UIConst.Expression, "CharacterUI/Expression"},

            {UIConst.TasksPanel, "TasksPanel/TasksPanel"},

            {UIConst.AimImage, "AimImage"},

            {UIConst.AudioUIManager, "AudioPanel/MainMenu"}
        };
    }

    public BasePanel OpenPanel(string name, bool isLockInput = false)
    {
        if (isLockInput)
        {
            EventCenter.Instance.EventTrigger(EventConst.LogoutInputSystem);
        }
        BasePanel panel = null;
        if(panelDict.TryGetValue(name, out panel))
        {
            return panel;
        }

        string path = "";
        if(!pathDict.TryGetValue(name, out path))
        {
            Debug.LogError("ç•Œé¢æ˜¾ç¤ºé”™è¯¯æˆ–æœªé…ç½®è·¯å¾„ï¼š" + name);
            return null;
        }

        GameObject panelPrefab = null;
        if(!prefabDict.TryGetValue(name, out panelPrefab))
        {
            string realPath = "Prefab/Panel/" + path;
            panelPrefab = Resources.Load<GameObject>(realPath);
            prefabDict.Add(name, panelPrefab);
        }
        GameObject panelObject = GameObject.Instantiate(panelPrefab, UIRoot, false);
        panel = panelObject.GetComponent<BasePanel>();
        panelDict.Add(name, panel);
        return panel;
    }

    public bool ClosePanel(string name, bool isLockInput = false)
    {   
        if (isLockInput)
        {
            EventCenter.Instance.EventTrigger(EventConst.ActiveInputSystem);
        }

        BasePanel panel = null;
        if(!panelDict.TryGetValue(name, out panel))
        {
            Debug.LogError("ç•Œé¢æœªæ‰“å¼€" + name);
            return false;
        }
        panel.ClosePanel(name);
        if(panelDict.ContainsKey(name))
        {
            panelDict.Remove(name);
        }
        return true;
    }

    public BasePanel OpenPanel(string name, Transform UIRoot)
    {   
        BasePanel panel = null;
        if(panelDict.TryGetValue(name, out panel))
        {
            
            return panel;
        }
        string path = "";
        if (!pathDict.TryGetValue(name, out path))
        {
            Debug.LogError("æœªé…ç½®è·¯å¾„ï¼š" + name);
            return null;
        }
        GameObject panelPrefab = null;
        if (!prefabDict.TryGetValue(name, out panelPrefab))
        {
            string realPath = "Prefab/Panel/" + path;
            panelPrefab = Resources.Load<GameObject>(realPath);
            prefabDict.Add(name, panelPrefab);
        }
        GameObject panelObject = GameObject.Instantiate(panelPrefab, UIRoot, false);
        panel = panelObject.GetComponent<BasePanel>();
        panelDict.Add(name, panel);
        if (panel == null)
        {
            Debug.Log("null");
            Debug.Log(panelDict.Keys);
        }
        Debug.Log(name+"  å°†è¢«ç”Ÿæˆ" );
        return panel;
    }

    public GameObject OpenGameObject(string name, Transform UIRoot)
    {
        string path = "";
        if (!pathDict.TryGetValue(name, out path))
        {
            Debug.LogError("æœªé…ç½®è·¯å¾„ï¼š" + name);
            return null;
        }
        GameObject panelPrefab = null;
        if (!prefabDict.TryGetValue(name, out panelPrefab))
        {
            string realPath = "Prefab/Panel/" + path;
            panelPrefab = Resources.Load<GameObject>(realPath);
            prefabDict.Add(name, panelPrefab);
        }
        GameObject panelObject = GameObject.Instantiate(panelPrefab, UIRoot, false);
        return panelObject;
    }

    private void OnDestroy()
    {
        // å½“ GameManager å®ä¾‹è¢«é”€æ¯æ—¶ï¼Œæ¸…ç†é™æ€å®ä¾‹å¼•ç”¨
        if (_instance == this)
        {
            _instance = null;
        }
    }


}
public class UIConst
{
    // é…ç½®åç§°

    // èƒŒåŒ…
    public const string PackagePanel = "PackagePanel";

    // åœºæ™¯
    public const string Item = "Item";
    public const string ItemDetail = "ItemDetail";
    public const string ItemsInfo = "ItemsInfo";
    public const string GunInfo = "GunInfo";
    public const string HealthBarUI = "HealthBarUI";
    public const string PlayerMainUI = "PlayerMainUI";
    public const string DialogBox = "DialogBox";
    public const string SelectBox = "DialogSelectBox";
    public const string TasksPanel = "TaskPanel";
    public const string AimImage = "AimImage";

    public const string AudioUIManager = "AudioUIManager"; 

    public const string LoadingScene = "LoadingScene";

    public const string Expression = "Expression";
}

public class UIImage
{
    public const string ä¸­æŒ‡ = "ä¸­æŒ‡";
    public const string æ€’ = "æ€’";
    public const string çˆ±å¿ƒ = "çˆ±å¿ƒ";
    public const string è‹¦ç¬‘ = "è‹¦ç¬‘"; // ğŸ˜…
    public const string æ„Ÿå¹å· = "æ„Ÿå¹å·";
    public const string å“­ = "å“­";
    public const string é—®å· = "é—®å·";
}
